#!/usr/bin/env python

import contextlib
import errno
import os
import shutil
import subprocess
import sys


SOURCE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
SRC_DIR = os.path.join(SOURCE_ROOT, 'vendor', 'chromium', 'src')


def main():
  os.chdir(SOURCE_ROOT)
  result = (subprocess.call(['git', 'submodule', 'sync']) or
            subprocess.call(['git', 'submodule', 'update',
                             '--init', '--recursive']))
  if result:
    return result

  # Clean out old checkout.
  if os.path.isdir(os.path.join(SRC_DIR, '.svn')):
    rm_rf(SRC_DIR)
  if os.path.isdir(os.path.join(SRC_DIR, '.git')):
    rm_rf(SRC_DIR)

  # Setup boto.
  with scoped_cwd(os.path.join('vendor', 'boto')):
    subprocess.call([sys.executable, 'setup.py', 'build'])


def rm_rf(path):
  try:
    shutil.rmtree(path)
  except OSError as e:
    if e.errno != errno.ENOENT:
      raise


@contextlib.contextmanager
def scoped_cwd(path):
  cwd = os.getcwd()
  os.chdir(path)
  try:
    yield
  finally:
    os.chdir(cwd)


if __name__ == '__main__':
  sys.exit(main())
