#!/bin/sh

set -e

cd "$(dirname $0)/.."
SOURCE_ROOT=$(pwd -P)
VENDOR_DIR="${SOURCE_ROOT}/vendor"
DEPOT_TOOLS_DIR="${VENDOR_DIR}/depot_tools"
NINJA="${DEPOT_TOOLS_DIR}/ninja"
CHROMIUM_DIR="${VENDOR_DIR}/chromium"

TARGETS="chromiumcontent gtest"

"${NINJA}" -C "${CHROMIUM_DIR}/src/out/Debug" ${TARGETS}
"${NINJA}" -C "${CHROMIUM_DIR}/src/out/Release" ${TARGETS}
