#!/usr/bin/env bash

set -e
set -o pipefail

rm -rf s3credentials
rm -fr src
rm -rf dist
rm -rf libchromiumcontent.zip
rm -rf libchromiumcontent-static.zip

cp ../config/s3credentials s3credentials

docker build -t libchromiumcontent-linux .

docker run \
  --rm \
  --env TARGET_ARCH="$TARGET_ARCH" \
  libchromiumcontent-linux /workspace/libchromiumcontent/script/cibuild
