#!/usr/bin/env python

import argparse
import contextlib
import errno
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import urllib2
import zipfile


SOURCE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

ARCH = {
  'cygwin': '32bit',
  'darwin': '64bit',
  'linux2': platform.architecture()[0],
  'win32': '32bit',
}[sys.platform]

PLATFORM_KEY = {
  'cygwin': 'win',
  'darwin': 'osx',
  'linux2': 'linux',
  'win32': 'win',
}[sys.platform]


class ProgramError(Exception):
  pass


def main():
  try:
    args = parse_args()
    if args.commit == 'HEAD':
      commit = head_commit()
    else:
      commit = args.commit
    base_url = '{0}/{1}/{2}'.format(args.url, PLATFORM_KEY, ARCH)
    download_if_needed(args.path, base_url, commit, force=args.force)
    if not args.static:
      download_static_libraries(args.path, base_url, commit)
    generate_filenames_gypi(args.path)
  except ProgramError as e:
    return e.message


def parse_args():
  parser = argparse.ArgumentParser(description='Download and extract '
                                   'libchromiumcontent')
  parser.add_argument('-f', '--force', action='store_true',
                      help='Overwrite destination if it already exists.')
  parser.add_argument('-c', '--commit', nargs='?', default='HEAD',
                      help='The commit of libchromiumcontent to download.')
  parser.add_argument('-s', '--static', action='store_true',
                      help='Download static_library build')
  parser.add_argument('url', help='The base URL from which to download '
                      '(i.e., the URL you passed to script/upload)')
  parser.add_argument('path', help='The path to extract to')
  return parser.parse_args()


def head_commit():
  cwd = os.getcwd()
  os.chdir(SOURCE_ROOT)
  try:
    args = ['git', 'rev-parse', 'HEAD']
    return subprocess.check_output(args).strip()
  finally:
    os.chdir(cwd)


def download_if_needed(destination, base_url, commit, force):
  version_file = os.path.join(destination, '.version')
  existing_version = ''
  try:
    with open(version_file, 'r') as f:
      existing_version = f.readline().strip()
  except IOError as e:
    if e.errno != errno.ENOENT:
      raise
  if existing_version == commit:
    return

  if force:
    rm_rf(destination)
  elif os.path.exists(destination):
    raise ProgramError('Error: {0} already exists. Pass --force if you '
                       'want to overwrite it.'.format(destination))
  sys.stderr.write('Downloading libchromiumcontent {0}...\n'.format(commit))
  sys.stderr.flush()
  download_and_extract(destination, '{0}/{1}/libchromiumcontent.zip'.format(base_url, commit))
  with open(version_file, 'w') as f:
    f.write('{0}\n'.format(commit))


def download_static_libraries(destination, base_url, commit):
  sys.stderr.write('Downloading static_library build of libchromiumcontent...')
  sys.stderr.flush()
  url = '{0}/{1}/libchromiumcontent-static.zip'.format(base_url, commit)
  download_and_extract(destination, url)


def download_and_extract(destination, url):
  print url
  with tempfile.TemporaryFile() as t:
    with contextlib.closing(urllib2.urlopen(url)) as u:
      while True:
        chunk = u.read(1024*1024)
        if not len(chunk):
          break
        sys.stderr.write('.')
        sys.stderr.flush()
        t.write(chunk)
    sys.stderr.write('\nExtracting...\n')
    sys.stderr.flush()
    with zipfile.ZipFile(t) as z:
      z.extractall(destination)


def generate_filenames_gypi(destination):
  generate = os.path.join(SOURCE_ROOT, 'tools', 'generate_filenames_gypi.py')
  subprocess.check_call([sys.executable, generate,
                         os.path.join(destination, 'filenames.gypi'),
                         os.path.join(destination, 'shared_library'),
                         os.path.join(destination, 'static_library')])


def rm_rf(path):
  try:
    shutil.rmtree(path)
  except OSError as e:
    if e.errno != errno.ENOENT:
      raise


if __name__ == '__main__':
  sys.exit(main())
