#! /bin/sh
# runhooks-mips64el script is doing the operation that "gclient sync --runhooks".
# Since many files do not support mips, for example node.
# get 'src/third_party/node/linux/node-linux-x64.tar.gz.sha1' from "gclient sync --runhooks",
# but is x86, not support mips.
# So Add --nohooks to "gclient sync" on mips, and write the script to get the file
# needed for build chromiumcontent instead of "gclient sync --runhooks".
# Author: Wang Qing
# Email: wangqing-hf@loongson.cn

# automatic gernerate ffmpeg build config files with mips64el.
pushd src/third_party/ffmpeg/
./chromium/scripts/build_ffmpeg.py linux mips64el
./chromium/scripts/copy_config.sh
./chromium/scripts/generate_gn.py
popd

# setup LASTCHANGE
pushd src/build/util
./lastchange.py > LASTCHANGE
./lastchange.py > LASTCHANGE.blink
popd

# Add node from system
if [ ! -f "src/third_party/node/linux/node-linux-x64/bin/node" ]; then
mkdir -p src/third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node src/third_party/node/linux/node-linux-x64/bin/node
fi

# Use npm install the necessary node modules
pushd src/third_party/node
if [ -f "package.json" ]; then
rm -v package.json
fi

if [ ! -d "node_modules/vulcanize" ]; then
npm install vulcanize
fi

if [ ! -d "node_modules/crisper" ]; then
npm install crisper
fi

if [ ! -d "node_modules/uglify-js" ]; then
npm install uglify-js
fi

if [ ! -d "node_modules/polymer-css-build" ]; then
npm install polymer-css-build
fi
popd

# Get skia/ext/skia_commit_hash.h 
python src/build/util/lastchange.py -m SKIA_COMMIT_HASH -s src/third_party/skia --header src/skia/ext/skia_commit_hash.h

