repo: src
patches:
-
  owners: alespergl
  file: build_gn.patch
  description: null
-
  owners: alespergl, deepak1556
  file: dcheck.patch
  description: |
    This disables some debug checks which currently fail when running the Electron
    test suite. In general there should be sustained effort to have all debug checks
    enabled. If you want to help, choose one of the diffs below and remove it. Then
    build Electron (debug configuration) and make sure all tests pass on the CI
    systems. Unfortunately the tests don't always cover the check failures, so it's
    good to also run some non-trivial Electron app to verify.

    Apart from getting rid of a whole diff, you may also be able to replace one diff
    with another which enables at least some of the previously disabled checks. For
    example, the checks might be disabled for a whole build target, but actually
    only one or two specific checks fail. Then it's better to simply comment out the
    failing checks and allow the rest of the target to have them enabled.

    Please keep the following lists updated.

    The ELECTRON_NO_DCHECK build flag disables debug checks universally.
    This patch applies the flag to the following GN targets:

      third_party/WebKit/Source/core/loader:loader
      url:url

    These files have debug checks explicitly commented out:

      base/memory/weak_ptr.cc
      base/process/kill_win.cc
      components/viz/service/display/program_binding.h
      content/browser/frame_host/navigation_controller_impl.cc
      content/browser/frame_host/render_frame_host_impl.cc
      content/browser/renderer_host/render_widget_host_view_mac.mm
      ppapi/host/ppapi_host.cc
      third_party/WebKit/Source/core/dom/Node.cpp
      third_party/WebKit/Source/platform/wtf/text/StringImpl.h
      ui/base/clipboard/clipboard_win.cc
-
  owners: zcbenz
  file: accelerator.patch
  description: null
-
  owners: alespergl
  file: allow_new_privs.patch
  description: null
-
  owners: null
  file: app_indicator_icon_menu.patch
  description: null
-
  owners: zcbenz
  file: blink_file_path.patch
  description: null
-
  owners: zcbenz
  file: blink_local_frame.patch
  description: |
    According to electron/electron#3699, it is unreliable to use |unload|
    event for process.exit('exit'), so we have to do that in
    willReleaseScriptContext.

    However Chromium then disallowed scripting in willReleaseScriptContext
    in https://codereview.chromium.org/1657583002, and crash will happen
    when there is code doing that.

    This patch reverts the change to fix the crash in Electron.
-
  owners: null
  file: blink_world_context.patch
  description: null
-
  owners: zcbenz
  file: browser_compositor_mac.patch
  description: null
-
  owners: null
  file: browser_plugin_wheel.patch
  description: null
-
  owners: null
  file: build_toolchain_win_patch.patch
  description: |
    Patch the Windows build toolchain to generate unique PDB names

    When the PDB files generated by the `static_library` build are
    packaged for distribution they are all copied to a single folder,
    some of the PDB files have identical names so they end up
    overwriting each other. The missing PDB files cause linker warnings
    when building Electron in Release mode, and make it more difficult
    to debug release builds.

    This patch modifies the PDB naming convention for the
    `static_library` build configuration to ensure PDB names are unique.
    For example, instead of generating `obj/ui/base/base_cc.pdb` the
    build will now generate `obj/ui/base/obj_ui_base_base_cc.pdb`.
-
  owners: zcbenz
  file: can_create_window.patch
  description: null
-
  owners: null
  file: compositor_delegate.patch
  description: null
-
  owners: null
  file: desktop_screen_win.patch
  description: null
-
  owners: zcbenz
  file: disable_hidden.patch
  description: null
-
  owners: zcbenz
  file: dom_storage_map.patch
  description: null
-
  owners: zcbenz, deepak1556
  file: frame_host_manager.patch
  description: null
-
  owners: tonyganch
  file: latency_info.patch
  description: null
-
  owners: zcbenz
  file: net_url_request_job.patch
  description: null
-
  owners: alexeykuzmin
  file: no_stack_dumping.patch
  description: null
-
  owners: deepak1556
  file: out_of_process_instance.patch
  description: null
-
  owners: alexeykuzmin
  file: protobuf_build_gn.patch
  description: null
-
  owners: null
  file: render_widget_host_view_base.patch
  description: null
-
  owners: zcbenz
  file: render_widget_host_view_mac.patch
  description: null
-
  owners: null
  file: scoped_clipboard_writer.patch
  description: null
-
  owners: deepak1556
  file: stream_resource_handler.patch
  description: null
-
  owners: null
  file: thread_capabilities.patch
  description: |
    Chromium automatically drops all capabilities of renderer threads in
    Linux, which may cause issues in a context like Electron, where the main
    and renderer threads are supposed to keep inherited permissions over the
    system.

    See https://github.com/atom/electron/issues/3666
-
  owners: zcbenz
  file: use_transparent_window.patch
  description: null
-
  owners: null
  file: web_contents.patch
  description: null
-
  owners: miniak
  file: webgl_context_attributes.patch
  description: null
-
  owners: null
  file: webview_cross_drag.patch
  description: null
-
  owners: zcbenz
  file: worker_context_will_destroy.patch
  description: null
-
  owners: null
  file: webui_in_subframes.patch
  description: null
-
  owners: alexeykuzmin
  file: export_blink_webdisplayitemlist.patch
  description: null
-
  owners: alexeykuzmin
  file: statically_build_power_save_blocker.patch
  description: null
-
  owners: gavignus
  file: browser_plugin_guest.patch
  description: null
-
  owners: alexeykuzmin
  file: disable_user_gesture_requirement_for_beforeunload_dialogs.patch
  description: See https://github.com/electron/electron/issues/10754
-
  owners: alexeykuzmin
  file: restore_adding_custom_cors_enabled_schemes.patch
  description: null
-
  owners: alexeykuzmin
  file: fix_blink_property_tree_state_to_tree_string_usage.patch
  description: Should probably be removed since we already have DCHECKs enabled.
-
  owners: deepak1556
  file: latency_histogram_macros.patch
  description: null
-
  owners: alexeykuzmin
  file: add_atomic_lib_to_dependencies_even_for_sysroot_builds.patch
  description: null
-
  owners: zcbenz
  file: gin_enable_disable_v8_platform.patch
  description: null
-
  owners: deepak1556
  file: disable-recursive-surface-sync.patch
  description: null
-
  owners: null
  file: can_disable_desktop_capture_throttling.patch
  description: null
-
  owners: deepak1556
  file: blink-worker-enable-csp-in-file-scheme.patch
  description: null
-
  owners: zcbenz
  file: fix-arm64-linking-error.patch
  description: Do not use system freetype for arm64
-
  owners: brenca
  file: disable-redraw-lock.patch
  description:  |
    Chromium uses a custom window titlebar implementation on Windows when DWM
    is disabled (Windows 7 and earlier, non Aero theme). The native titlebar
    sometimes painted over this custom titlebar, so a workaround was put in
    place to lock redraws in reaction to certain events if DWM is disabled,
    since the code assumes that in that case, the custom titlebar is painted.
    Electron forces the use of the native titlebar, which the workaround doesn't
    take into account, and still locks redraws, causing weird repainting issues
    in electron (and other applications). This patch provides a way to disable
    the redraw locking mechanism, which fixes these issues. The electron issue
    can be found at https://github.com/electron/electron/issues/1821
-
  owners: jkleinsc
  file: backport_4dabe8070550.patch
  description:  |
    Backports part of 4dabe8070550cb4014d1f996aa1a7e130bef42e1 so that we don't
    need the native_client source tree.
